config/routes.rb
Gendec::Application.routes.draw do
  get "users/new"

   
  root to: 'static_pages#home'
  match '/home',    to: 'static_pages#home'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/signup',  to: 'users#new'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @page_title = "Dashboard"
  end

  def help
    @page_title = "Help"
  end
  
  def contact
    @page_title = "Contact"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @page_title = "Sign up"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def full_title(page_title)
     base_title = "GenDec"
     if page_title.empty?
       base_title
     else
       "#{base_title} | #{page_title}"
     end
   end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://gendecgen.com/">Gen Dec Gen</a>
    by Phil Balderson
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li>All rights reserved. No warranty implied or offered.</li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "GENDEC", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_path %></li>
          <li><%= link_to "Help",    help_path %></li>
          <li><%= link_to "Sign in", '#' %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title%></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>   
  </head>
  <body>
    <%= render 'layouts/header' %>   
    <div class="container">
      <%= yield %>
    </div>

 <%= render 'layouts/footer' %>   
  </body>
</html>

app/views/static_pages/contact.html.erb
<h1>GenDec Contact</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<h1>GenDec Help Page</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>
<p>title = <%= @page_title%>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
 <h1>GenDec Dashboard</h1>

  <h2>
    This is the home page for the
    <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

  <%= link_to "Sign up now!", signup_path , class: "btn btn-large btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>

app/views/users/new.html.erb
<h1>Sign up</h1>
<p>Find me in app/views/users/new.html.erb</p>